### ISSUE TITLE
generate HLS url from Aws Kinesis video stream using java sdk

### ISSUE THREAD

**Issue by amiya-elear** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#105]
Hi Team,
How can I generate an HLS link for live stream using kinesis ava SDK?
**step 1: to get data endpoint I have written code to generate data endpoint in java kinesis** 

final AmazonKinesisVideo frontendClient = AmazonKinesisVideoAsyncClient.builder()
                    .withCredentials(AuthHelper.getSystemPropertiesCredentialsProvider())
                    .withRegion(DEFAULT_REGION)
                    .build();
            /* this is the endpoint returned by GetDataEndpoint API */
            final String dataEndpoint = frontendClient.getDataEndpoint(
                    new GetDataEndpointRequest()
                            .withStreamName(STREAM_NAME)
                            .withAPIName("GET_HLS_STREAMING_SESSION_URL")).getDataEndpoint();
            System.out.println("data end point************"+ dataEndpoint);

**step2: use GetHLSStreamingSessionURLRequest  to get HLS url for live stream**

final AmazonKinesisVideoArchivedMedia gethlsurl = AmazonKinesisVideoArchivedMediaClient.builder()
                    .withCredentials(AuthHelper.getSystemPropertiesCredentialsProvider())
                    .withRegion(DEFAULT_REGION)
                    .build();
            GetHLSStreamingSessionURLRequest req = new GetHLSStreamingSessionURLRequest()
                    .withDisplayFragmentTimestamp("NEVER")
                    .withExpires(600)
                    .withStreamName(STREAM_NAME)
                    .withPlaybackMode("LIVE")
                    .withDiscontinuityMode("ALWAYS")
                    .withContainerFormat("FRAGMENTED_MP4");
            final String hlsurl = gethlsurl.getHLSStreamingSessionURL(req).getHLSStreamingSessionURL();
            System.out.println("data end point************"+ hlsurl);

I am able to generate data endpoint and its printing correct value but, I am getting ERROR while generating HLS url 
"Exception in thread "main" com.amazonaws.services.kinesisvideo.model.AmazonKinesisVideoException: null (Service: AmazonKinesisVideoArchivedMedia; Status Code: 403; Error Code: null;"

query1: 
Do I need to pass explicitly retrieved endpoint while generating HLSStreamingSessionURL? if yes can you guide me on how can I pass data endpoint to generate  HLSStreamingSessionURL? or if not then how can I get it using java kinesis SDK

**Comment by lherman-cs** [comment]
@amiya-elear you can modify your AmazonKinesisVideoArchivedMediaClient to be:

```java
final AmazonKinesisVideoArchivedMedia gethlsurl = AmazonKinesisVideoArchivedMediaClient.builder()
.withCredentials(AuthHelper.getSystemPropertiesCredentialsProvider())
.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(dataEndpoint, DEFAULT_REGION)) // <-- Notice that there's no  .withRegion(DEFAULT_REGION)
.build();
```

**Comment by amiya-elear** [comment]
Thank you so much Lukas Herman, after passing retrieved dataEndpoint I am able to get HLS URL,

I have one small question now I am reading audio and video data from a single file frame by frame as 

private static final String FRAME_DIR = "src/main/resources/data/audio-video-frames";
private static MediaSource createFileMediaSource() {
        final AudioVideoFileMediaSourceConfiguration configuration =
                new AudioVideoFileMediaSourceConfiguration.AudioVideoBuilder()
                        .withDir(FRAME_DIR)
                        .withRetentionPeriodInHours(RETENTION_ONE_HOUR)
                        .withAbsoluteTimecode(ABSOLUTE_TIMECODES)
                        .withTrackInfoList(DemoTrackInfos.createTrackInfoList())
                        .build();
        final AudioVideoFileMediaSource mediaSource = new AudioVideoFileMediaSource(STREAM_NAME);
        mediaSource.configure(configuration);
        return mediaSource;

I want to read audio and video data from 2 separate data point means buffer where my camera witing audio and video, I want to read those two buffer pointer and write audio and video data (encoded audio and video file with timestamp)  into Kinesis video stream,  can you help me how can I do that using kinesis java producer sdk if you have any document with sample example you can share I will go through and implement the same.

**Comment by lherman-cs** [comment]
@amiya-elear since the original question has been answered, I'll mark this issue as resolve. To help a larger community, I'd like to separate these 2 issues so that people can find the answer easier, https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/106.
