### ISSUE TITLE
Loading native library KinesisVideoProducerJNI failed

### ISSUE THREAD

**Issue by sambithota** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#12]
I am facing the same issue while running the sample in my local. I am getting this.
EXCEPTION: UnsatisfiedLinkError: Unsatisfied link error. Loading native library KinesisVideoProducerJNI failed with java.lang.UnsatisfiedLinkError
Because libKinesisVideoProducerJNI.dll is not present. How to generate this on windows machine?

**Comment by zhiyua-git** [comment]
Thanks for reaching out, we are still looking into the WIndows build and hope to get the Windows solution out soon.

**Comment by unicornss** [comment]
We will publish once we get the Windows Build for Kinesis Video Streams. in our roadmap.  

Closing this for now.

Thanks
-SS

**Comment by mocampo78** [comment]
Hi...

Do you have a date to publish libKinesisVideoProducerJNI.dll ?

Still is not working in Windows 

Thanks

**Comment by MushMal** [comment]
@mocampo78 thanks for your feedback. We are working on it. Unfortunately, we don't have an exact date currently. We will communicate as soon as we have a set date.

**Comment by CedszxcJulian** [comment]
Hi, 

Still working on KinesisVideoProducerJNI.dll? :) 

Thank you & Kind Regards,
Ced

**Comment by zhiyua-git** [comment]
@CedszxcJulian 

Yes, windows build is on our roadmap. We will communicate as soon as we have a set date.

Thanks,
-ZH

**Comment by arunsridher** [comment]
Hey it got resolved for me by doing this
Right click on your project and go to **Java Build Path** then **Libraries** and under **Maven Dependencies** go to **Native Library Location**
Click on it and go to **Edit** and set the **Location Path** to /absolute path/to/amazon-kinesis-video-streams-producer-sdk-java/src/main/resources/lib/windows

I was initially **None**
I'm using windows and eclipse
