### ISSUE TITLE
How to check for persisted data in kinesis video stream

### ISSUE THREAD

**Issue by amiya-elear** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#127]
Hi Team,

I want to check for persisted data in the kinesis video stream before consuming data from the stream. Can you guys help me with how to check for persisted data in the kinesis video stream?

Thanks.

**Comment by MushMal** [comment]
Check out ListFragment API in the backend documentation

**Comment by disa6302** [comment]
Closing assuming the question is answered. Feel free to open a new issue if you have any questions.
