### ISSUE TITLE
[QUESTION] Java sdk on android oreo

### ISSUE THREAD

**Issue by mechavarriahipcam** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#141]
Hello,
I am about to start a development on a proprietary architecture that runs an android Oreo, aarch64-linux-android.
With the android sdk I get a green image at kinesisi console. and apparently it is not supported.
Is it possible to use the java-sdk to develop the app?

**Comment by niyatim23** [comment]
Hi @mechavarriahipcam, do you mean to use the Java SDK for Android development? The supported OSs for this repository are MacOS, Windows and Ubuntu. I'm not sure if the build will be supported.

Closing assuming answered
