### ISSUE TITLE
KVS Audio Only Streaming

### ISSUE THREAD

**Issue by mudassir-mukhtar-ahmed** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#144]
Hello,

I'm looking to use KVS to stream audio only. Currently able to stream audio using c++ producer gstreamer plugin on my system with the below command.

gst-launch-1.0 -v kvssink name=sink stream-name="teststream" access-key="" secret-key="" aws-region="us-east-1" osxaudiosrc ! audioconvert ! avenc_aac ! queue ! sink.

However i'm unable to playback the stream using HLS or DASH because the API expects the stream to have a video encoded in H264 to generate a HLS or DASH streaming url. AWS Enterprise support recommended a work around to send a static image along with the audio stream to playback successfully. However i'm unable to figure out how to do that from the gstreamer docs. Appreciate if someone can help on how to stream audio with a static image ( or a sample video? ) to enable HLS or DASH playback. We're open to using either c++ or java producer depending upon whichever helps us achieve our use case.

**Comment by hassanctech** [comment]
closing, same issue as: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/734
