### ISSUE TITLE
errorCode=FRAGMENT_TIMECODE_LESSER_THAN_PREVIOUS, errorId=4004

### ISSUE THREAD

**Issue by LukeLinXu** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#145]
Hey there,

we are trying to upload video file to Kinesis, but got this 4004 error. can you help troubleshoot what's wrong with this video file? I don't see b-frame in it.
[2021-08-20T19-43-12.48.mkv.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/files/7023860/2021-08-20T19-43-12.48.mkv.zip)

Thank you.

**Comment by niyatim23** [comment]
Closing since the issue is stale. Feel free to reopen it if it still persists
