### ISSUE TITLE
How did you generate h264 files?

### ISSUE THREAD

**Issue by LittleWat** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#149]
I would like to put split image(jpg) files into kinesis video stream.

There is a sample and it uses [.h264 files ](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/tree/master/src/main/resources/data/h264)

How did you convert jpg to this h264 file?

**Comment by disa6302** [comment]
@LittleWat , 

GStreamer is the most popular tool to do the job. You can look at GStreamer forums to see how this conversion can be done.

**Comment by LittleWat** [comment]
[Just Memo] I could send jpeg to KVS like the code below;
https://github.com/LittleWat/kvs-jpeg-java/blob/7ebb1b8854c54768799d1285563cc4a7dc75138b/src/main/java/com/cityos/kvs/JpegToKvs.java
