### ISSUE TITLE
Kinesis Live Stream Displayed on Android App using Java

### ISSUE THREAD

**Issue by ricamano** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#161]
Hey there, sorry in advance if this isn't the right place but I'm new to GitHub and for some reason, I could not open an issue in the Android Repository, so I'm trying my luck here.

I have been working on an Android App with the intention of building my own security system using Amazon Web Services. I have been able to use other AWS services like S3 and Cognito, and up until this point, I was able to stream from a camera connected to my raspberry pi to the AWS website, where I could see it there. The problem is that I can't seem to find a way to get this stream and display it on my android app. I have seen a lot of documentation online but I'm way too confused about it (I'm new to programming and in my opinion i could not find a step-by-step guide for this problem). I have also tried to download their repositories and run the apps, yet I'm unable to make them work (usual the error was that it couldn't create a Kinesis Video Client even tho i made sure to setup the credentials and region properly). Therefore, if anyone is able to help me out with the coding regarding getting a Kinesis stream and displaying it on a android app it would mean a lot to me. Also, i have seen that with GetMedia API i could get what i want regarding to get my stream while after i just needed to display it, but i cant find any step-by-step implementation or all the coding that its involved in it. Thank you for your time

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to open another issue if the problem persists
