### ISSUE TITLE
Fail to use custom mkv 

### ISSUE THREAD

**Issue by SelniumTest** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#19]
hi , i run PutMediaDemo.java and replace cluster.mkv to my xxxx.mkv , but  i am getting below error message : 
onAckEvent AckEvent{ackEventType=ERROR, fragmentTimecode=null, fragmentNumber='null', errorCode=MORE_THAN_ONE_TRACK_FOUND, errorId=4005}

**Comment by SelniumTest** [comment]
Hi zhiyua-git , 

I use single-MKV-track MKV and it's works , thanks.

**Comment by Rishabhadept** [comment]
Hi,

I am facing the same error. And I am not able to understand what does it mean when error says:  "More than one track" in MKV? I have tried different videos in MKV format (with audio, without audio, single frame throughout the video, recorded video) but this same error occurs. 

Can you please help me with what is "single MKV track" video?
