### ISSUE TITLE
Issues building on Mac High Sierra (10.13.1)

### ISSUE THREAD

**Issue by lhamregit** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#2]
When trying to run the Mac install script, getting this error;

connect.c:1069:12: error: 'connectx' is only available on macOS 10.11 or newer [-Werror,-Wunguarded-availability]
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
/usr/include/sys/socket.h:713:5: note: 'connectx' has been explicitly marked partial here
int connectx(int, const sa_endpoints_t *, sae_associd_t, unsigned int,
    ^
connect.c:1069:12: note: enclose 'connectx' in a __builtin_available check to silence this warning
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
1 error generated.
make[2]: *** [libcurl_la-connect.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by MushMal** [comment]
Apparently, this was due to libcurl v 7.55 on latter versions of Mac OS. We have updated the install-script in the cpp SDK. Please clear the repository and try with the new script.
