### ISSUE TITLE
README Update for KinesisVideoProducerJNI

### ISSUE THREAD

**Issue by nicklee1990** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#24]
I think it would be helpful for users if it is made explicitly clear in the README that the CPP `install-script` needs to be ran in order to run the demo as it isn't obvious from the current instructions. It is mentioned [here](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-javaapi.html) that you must build from source to get the "KinesisVideoProducerJNI" library but this information should probably be present in the README section of this repo where the KinesisVideoProducerJNI library is mentioned this repo can presumably be consumed independent of the tutorial in the official docs?

Just a suggestion rather than an issue

**Comment by MushMal** [comment]
Thanks for your feedback. We will incorporate it with the next iteration.
