### ISSUE TITLE
Eclipse Build Error

### ISSUE THREAD

**Issue by francoisdutoit** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#27]
Hi,

I'm getting the following build error in Eclipse on Ubuntu 17.10

"Build path specifies execution environment JavaSE-1.7. There are no JREs installed in the workspace that are strictly compatible with this environment." kinesisvideo-java-demo

As per Install Steps for Ubuntu 17.x I installed openjdk-8-jdk

I have done all the prerequisites as per Ubuntu installation instrauctions.
Also - I'm getting a bunch of java errors when opening the project.  ( See attached screenshot )
Thanks!

![screenshot from 2018-02-20 20-56-11](https://user-images.githubusercontent.com/9386768/36443350-22c9ca0e-1681-11e8-96eb-748cb41a3b0a.png)

**Comment by zhiyua-git** [comment]
Hi francoisdutoit,

From the error in your screenshot, it is a known Lombok issue with Eclipse.

Can you try the solution mentioned in this [issue](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/17)? 

Let me know if it works. 

Thanks,
-ZH

**Comment by francoisdutoit** [comment]
Thanks!
