### ISSUE TITLE
Docker Demo requires running install-script

### ISSUE THREAD

**Issue by smp** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#35]
Hello,

I ran through the docker demo application today and hit an issue whereby I was missing links to the requisite libraries. The solution was to run the install scripts in the following directory and accept an agreement to use them.

`/opt/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build`

I'm happy to update the README documentation for the docker demo, but wanted to check that we couldn't automagically do this on behalf of the user.

**Comment by MushMal** [comment]
@smp thanks a lot for the information. Please do proceed with a pull request. We will evaluate it asap.

**Comment by smp** [comment]
done! https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/pull/36

**Comment by MushMal** [comment]
Perfect! Thanks. I will go ahead and resolve this
