### ISSUE TITLE
set the configure and throttle the video issue

### ISSUE THREAD

**Issue by jis1218** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#43]
Hello!

I had some issues to set configuration. I wanted to adjust frame rate using CameraMediaSourceConfiguration.Builder().
But it seemed to not work. I put 1 to withFrameRate(int rate) as a parameter but 'video preview' showed the stream smoothly.

```
final CameraMediaSourceConfiguration configuration =
	new CameraMediaSourceConfiguration.Builder()
.withFrameRate(FPS_1)
.withEncodingBitRate(100000)
```
I found that it is related to DiscreteTimePeriodsThrottler.java. There is an explanation above, but it is hard to understand. Can anybody explain easily? Or What should I study for understanding? Any link will be helpful. What is encoding bit rate?

Also, in case of horizontal and vertical resolution, I set them as 640 and 480 respectively, but 'video preview' resolution said 1280x720. Here is the code.
```
final CameraMediaSourceConfiguration configuration =    			
    			.withHorizontalResolution(640)
    			.withVerticalResolution(480)
    			.build();
```
How do I change thevertical and horizontal resolution?
Thank you in advance.

**Comment by MushMal** [comment]
Resolving as stale/no response.
