### ISSUE TITLE
GetMedia API. How does it work?

### ISSUE THREAD

**Issue by RafaelRViana** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#47]
Hi,

I have configured the GStreamer plugin as a producer sending streaming from an IP camera to Kinesis trough RTSP.

Now, I want to get each frame as image to do some video analytics (OpenCV pre-processing + DL recognition).

What is the easiest way to get these frames?
I see the Rekognition has a direct integration trough ARN Stream. However, I don't want to use this service.
1) Is there a easy way to send the image frames directly to S3? (directly from ARN?)
2) Or the unique way is to get it trough GetMedia API in Java?

I'm following this doc to use GetMediaAPI:
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-renderer.html

However, even KinesisVideoExample and KinesisVideoRendererExample use InputStream as argument and execute both GetMediaWorker and PutMediaWorker. I changed the code to not execute PutMediaWorker (since my GStreamer producer is already sending frames to this stream). And also commented this streamOps.recreateStreamIfNecessary(); (to not recreate stream in AWS).

But, I can't read stream.

Where can I find one example showing how to read an already existing stream (without put anything)?

**Comment by zhiyua-git** [comment]
Hi @RafaelRViana ,

You are doing it in the right way, by commenting out PutMediaWorker and streamOps.recreateStreamIfNecessary() you should be able to get data with GetMedia from provided stream name.

1. Can you check if you have the file kinesis_video_example_merged_output2.mkv in your amazon-kinesis-video-streams-parser-library directory? That is the default output file name in the sample code.
2. The parser library is picking up AWS credentials from profile, can you confirm you were using the same credentials and region in the parser library as what you used in your producer?

-ZH

**Comment by vijaygj** [comment]
Hello @RafaelRViana ,

If you are still observing problems after using @zhiyua-git 's recommendation, can you please provide aws request ids for the Get calls? We can check on the server side what is going on. You can send the logs To: kinesis-video-support@amazon.com

Thanks,
Vijay.

**Comment by RafaelRViana** [comment]
Java Output:
```
Start GetMedia worker on stream {}Test
GetMedia called on stream {} response {} requestId {}Test200fe27ac82-6354-091f-aa2c-c20e0da9bb60
StreamingMkvReader created for stream {} Test
Start of segment  {} 1
End of segment  {} fragment # {} millisBehindNow {} 19134385233318143239268206261427385745515954322179079109
Start of segment  {} 2
End of segment  {} fragment # {} millisBehindNow {} 29134385233318143239763382277141537872462898752879078620
Start of segment  {} 3
End of segment  {} fragment # {} millisBehindNow {} 39134385233318143240258558292855689988448343246279078578
Start of segment  {} 4
End of segment  {} fragment # {} millisBehindNow {} 49134385233318143240753734308569842100059362076079078618
```

KinesisVideoExampleTest.java
```
public class KinesisVideoExampleTest {
    
	@Test
    public void testExample() throws InterruptedException, IOException {
		AWSCredentialsProvider awsCredentialsProvider = new AWSCredentialsProvider() {
			
			public static final String AWS_ACCESS_KEY = "MY_ACCESS_KEY";
		    public static final String AWS_SECRET_KEY = "MY_SECRET_KEY";

			@Override
			public AWSCredentials getCredentials() {
				return new BasicAWSCredentials(AWS_ACCESS_KEY, AWS_SECRET_KEY);
			}

			@Override
			public void refresh() {
				
			}
		};
		KinesisVideoExample example = KinesisVideoExample.builder().region(Regions.US_WEST_2)
                .streamName("Test")
                .credentialsProvider(awsCredentialsProvider)
                .inputVideoStream(**null**)
                .build();

        example.execute();
        //Assert.assertEquals(8, example.getFragmentsPersisted());
        Assert.assertEquals(8, example.getFragmentsRead());
    }
}
```

My ARN of Kinesis VideoStream: arn:aws:kinesisvideo:us-west-2:140265381894:stream/Test/1536178017340
It's streaming correctly to the Kinesis VideoStream but the Java code generated the kinesis_video_example_merged_output2.mkv with same content then clusters.mkv.

**Comment by zhiyua-git** [comment]
Hi @RafaelRViana ,

Can you change[ this line](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java#L107) to

new StartSelector().withStartSelectorType(StartSelectorType.**NOW**),

This will read for the TIP of your stream. When you are reading from earliest, you were likely reading the content you sent into the stream with PutMediaWorker. 

We will update the example to make GetMedia from existing stream easier.

-ZH

**Comment by RafaelRViana** [comment]
@zhiyua-git Perfect! Thank you. That's it.

**Comment by garishsood** [comment]
Hi @RafaelRViana, 
My name is Girish and I am the product manager for Kinesis Video. Would you mind sending a note describing your usecase to my email id: garisood@amazon.com? 
We are continuously working on new features to make things easy for developers and we may have something in works that fits your needs. 
Look forward to learning more about your how you plan to use Kinesis Video.

**Comment by RafaelRViana** [comment]
Hi @garishsood . Sent e-mail to you.

**Comment by zhiyua-git** [comment]
Closing the issue for now.
For additional details and support, please reach out to kinesis-video-support@amazon.com with your specific video streaming use case with audio. Thanks

**Comment by hameedriswan7** [comment]
hola dev,
    i need clarification for storing kinesis video stream to S3. i can able to stream RTSP Video in AWS using Putmedia. but i need to store the RTSP Video in S3 is Getmedia is correct approach to stroing?
can anyone share valid example or class file.

**Comment by zhiyua-git** [comment]
@hameedriswan7 This sample can help you retrieve your video into file. https://github.com/aws/amazon-kinesis-video-streams-parser-library#kinesisvideoexample

**Comment by hameedriswan7** [comment]
Hello @zhiyua-git  By using GetMedia i can get this response :
getMedia: {ContentType: video/webm,Payload: com.amazonaws.util.ServiceClientHolderInputStream@1df8b5b8}
contentType: video/webm
streamname: KVS5Tv1D4Iv8eP903L
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/workspace-sts/optisol-camera-kinesis_new_ui/optisol-camera-kinesis/lib/slf4j-simple-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Administrator/.m2/repository/org/slf4j/slf4j-jdk14/1.7.26/slf4j-jdk14-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Administrator/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[main] INFO com.amazonaws.kinesisvideo.parser.ebml.EBMLParser - Creating EBMLParser with maxContentBytesInOnePass 8192
mkvReader com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader@6f6745d6

iam getting payload result like "com.amazonaws.util.ServiceClientHolderInputStream@1df8b5b8}" is this chunk video? how can i preview this. to check whether its belongs to KVS.

**Comment by zhiyua-git** [comment]
Hi @hameedriswan7 ,

Run this sample https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/test/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExampleTest.java#L49 and you will get the output file as kinesis_video_example_merged_output2.mkv. https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java#L199

It can be playback with VLC if you want to verify.

**Comment by hameedriswan7** [comment]
i have added this things only to my code:

AmazonKinesisVideoMediaClientBuilder builder = AmazonKinesisVideoMediaClientBuilder.standard()
				.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endPoint, region))
				.withCredentials(credentialsProvider);

		StartSelector StartSelector = new StartSelector().withStartSelectorType("NOW");

		GetMediaRequest getMediaRequest = new GetMediaRequest().withStartSelector(StartSelector)
				.withStreamName("KVS5Tv1D4Iv8eP903L");

		GetMediaResult getMediaResult = builder.build().getMedia(getMediaRequest);

		System.out.println("getMedia: " + getMediaResult);
		System.out.println("contentType: " + getMediaResult.getContentType());
		System.out.println("streamname: " + getMediaRequest.getStreamName());
//		System.out.println("getReadLimit: "+getMediaRequest.));
		
				
		
		StreamingMkvReader mkvReader = StreamingMkvReader
				.createDefault(new InputStreamParserByteSource(getMediaResult.getPayload()));
		
		System.out.println("mkvReader " + mkvReader);
		
		FragmentMetadataVisitor fragmentMetadataVisitor = FragmentMetadataVisitor.create();

        //A visitor used to log as the GetMedia stream is processed.
//        LogVisitor logVisitor = new LogVisitor(fragmentMetadataVisitor);
		

		  OutputStream fileOutputStream = Files.newOutputStream(Paths.get("kinesis_video_example_merged_output2.mkv"),
                  StandardOpenOption.WRITE, StandardOpenOption.CREATE);
          BufferedOutputStream outputStream = new BufferedOutputStream(fileOutputStream);
          OutputSegmentMerger outputSegmentMerger = OutputSegmentMerger.createDefault(outputStream);
          System.out.println("outputSegmentMerger "+outputSegmentMerger);
          
          
          CompositeMkvElementVisitor mkvElementVisitor = 
        		  new CompositeMkvElementVisitor(fragmentMetadataVisitor,outputSegmentMerger);
          
          System.out.println("mkvElementVisitor: "+mkvElementVisitor);

Output Iam getting:
GetMediaResult : getMedia: {ContentType: video/webm,Payload:com.amazonaws.util.ServiceClientHolderInputStream@1df8b5b8}

and OutputSegmentMerger : com.amazonaws.kinesisvideo.parser.utilities.OutputSegmentMerger@1acaf3d 

"kinesis_video_example_merged_output2.mkv " create while running  this code but in 0Kb. cannot open it.

is that code is correct.? TestCase are needed? 

i am not added all the class mention in https://github.com/aws/amazon-kinesis-video-streams-parser-library

**Comment by zhiyua-git** [comment]
@hameedriswan7 You need to apply your visitor. 
mkvStreamReader.apply(mkvElementVisitor);

If adding this still doesn't work for you, I would recommend starting with the KinesisVideoExampleTest as it is tested as a working sample.

**Comment by hameedriswan7** [comment]
i added like this only still same output. 

need one clarification  there is connection between OutputSegmentMerger  and Mkvreader how we get video

final MkvElementVisitor elementVisitor = null;

StreamingMkvReader mkvReader = StreamingMkvReader
				.createDefault(new InputStreamParserByteSource(getMediaResult.getPayload()));
		
		System.out.println("mkvReader " + mkvReader);
		
		try {
			mkvReader.apply(elementVisitor);
		} catch (Exception e) {
		}

**Comment by zhiyua-git** [comment]
@hameedriswan7 ,

These are the connection between getMedia output, mkv reader, output segment merger. You need to have data getting into the stream to get output on GetMedia side as you are using StartSelector.NOW. For more information you can refer to https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_GetMedia.html

StreamingMkvReader mkvReader = StreamingMkvReader
			.createDefault(new InputStreamParserByteSource(getMediaResult.getPayload()));
CompositeMkvElementVisitor mkvElementVisitor = 
    		  new CompositeMkvElementVisitor(fragmentMetadataVisitor,outputSegmentMerger);
 mkvReader.apply(mkvElementVisitor);

**Comment by hameedriswan7** [comment]
@zhiyua-git  Thank you so much. Now i van able view the KVS video in vlc. Again Thanks for the Support.

**Comment by hameedriswan7** [comment]
@zhiyua-git  Using above code i get single video output of KVS but i need chunked video ?

**Comment by zhiyua-git** [comment]
@hameedriswan7 What do you mean by single video v.s. chunked video?

**Comment by hameedriswan7** [comment]
@zhiyua-git  
This line combine provide multiple to single:
//An OutputSegmentMerger to combine multiple segments that share track and ebml metadata into one
	    //mkv segment.
		OutputSegmentMerger outputSegmentMerger = OutputSegmentMerger.createDefault(outputStream);
		System.out.println("outputSegmentMerger " + outputSegmentMerger);
		
But i need to store single stream like segment multiple video of single stream with low size.Now i can get merged video but i need to split it while get. Is any possible way to store that Getmedia KVS video to S3 directly?

**Comment by zhiyua-git** [comment]
@hameedriswan7 ,  we don’t have such kind of API/sample right now, if you want to store multiple video files(i.e. for each fragment) into S3, the approach you can use now is adding an MKV EBML element visitor and split output of GetMedia into small files and upload to S3.

If you want to submit a feature request for storing multiple video into S3. You can open a GitHub issue in Kinesis video parser library repository. Thanks.

**Comment by hameedriswan7** [comment]
@zhiyua-git  can you suggest any refer for MKV EBML element visitor and split output of GetMedia into small files and upload to S3.?

Thanks and regards

**Comment by zhiyua-git** [comment]
@hameedriswan7 You can do similar process as [CopyVisitor](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/b72c4d82a1856ad66cb74430f82dcdbfce5dabe2/src/main/java/com/amazonaws/kinesisvideo/parser/mkv/visitors/CopyVisitor.java#L47). Create your FragmentVisitor extends MkvElementVisitor. 
Then in visit(MkvStartMasterElement startMasterElement) 
`if (startMasterElement.getElementMetaData().getTypeInfo().equals(MkvTypeInfos.EBML)) {
            // set output channel to your new file based on your file name format
        }
        startMasterElement.writeToChannel(outputChannel);`

In this way you will get the small files and if you want to just send the data from outputChannel to S3, you might not even need to store as file.

**Comment by hameedriswan7** [comment]
@zhiyua-git  i have added above codes in my code shown below and i commented some lines...is that correct way to proceed. i didnt get any video segments..its terminated...

		 fileOutputStream = Files.newOutputStream(Paths.get("kinesis_video_merged_output.mkv"),
				StandardOpenOption.WRITE, StandardOpenOption.CREATE);
//		BufferedOutputStream outputStream = new BufferedOutputStream(fileOutputStream);
		
		//An OutputSegmentMerger to combine multiple segments that share track and ebml metadata into one
	    //mkv segment.
//		OutputSegmentMerger outputSegmentMerger = OutputSegmentMerger.createDefault(outputStream);
//		System.out.println("outputSegmentMerger " + outputSegmentMerger);
//		
//		
//		
//
//		FragmentMetadataVisitor fragmentMetadataVisitor = FragmentMetadataVisitor.create();
//
//		// A composite visitor to encapsulate the three visitors
//		CompositeMkvElementVisitor mkvElementVisitor = new CompositeMkvElementVisitor(fragmentMetadataVisitor,
//				outputSegmentMerger);
//
//		System.out.println("mkvElementVisitor: " + mkvElementVisitor);
//		
//		StreamingMkvReader mkvReader = StreamingMkvReader
//				.createDefault(new InputStreamParserByteSource(getMediaResult.getPayload()));
//
//		System.out.println("mkvReader " + mkvReader);
//
//		try {
//
//			while (mkvReader.mightHaveNext()) {
//				Optional<MkvElement> mkvElement = mkvReader.nextIfAvailable();
//				if (mkvElement.isPresent()) {
//					mkvElement.get().accept(mkvElementVisitor);
//				}
//			}
//		} catch (Exception e) {
//		}
		
	}
	
	WritableByteChannel outputChannel;
	@Override
	public void visit(MkvStartMasterElement startMasterElement) throws MkvElementVisitException {
		System.out.println("startMasterElement........");
			if(startMasterElement.getElementMetaData().getTypeInfo().equals(MkvTypeInfos.EBML)) {
				outputChannel = Channels.newChannel(fileOutputStream);
				System.out.println("startMasterElement........");
			}
			
			startMasterElement.writeToChannel(outputChannel);
			System.out.println("startMasterElement Outside");
	}

**Comment by zhiyua-git** [comment]
@hameedriswan7 As you are trying to get multiple files then you will need to provide multiple FileOutputStreams pointing to different files, I think you will get Exception by doing Channels.newChannel() on same file without closing it.

You also need this to write all the contents: https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/b72c4d82a1856ad66cb74430f82dcdbfce5dabe2/src/main/java/com/amazonaws/kinesisvideo/parser/mkv/visitors/CopyVisitor.java#L56

**Comment by hameedriswan7** [comment]
@zhiyua-git  yes may be...i can refer above documents and will try. Thank you.

**Comment by hameedriswan7** [comment]
@zhiyua-git  above link i have referred im not getting proper way to send the partition  of getmedia video storing  to S3. 

This Below line make getmedia as single video. but need segment video like Half Hours once of KVS stream in S3.
//An OutputSegmentMerger to combine multiple segments that share track and ebml metadata into one
	    //mkv segment.
		OutputSegmentMerger outputSegmentMerger = OutputSegmentMerger.createDefault(outputStream);
		System.out.println("outputSegmentMerger " + outputSegmentMerger);

**Comment by zhiyua-git** [comment]
@hameedriswan7 Sounds like you need a feature that supports getting a duration of video into file, can you open a feature request issue on https://github.com/aws/amazon-kinesis-video-streams-parser-library? Thanks.

**Comment by ahmedha** [comment]
@hameedriswan7  Were you able to get the chunking of video streams to work by using any low level API?  I am trying to store the video in time length chunks (1 hr or 30 min).
