### ISSUE TITLE
native windows lib missing

### ISSUE THREAD

**Issue by pmtolk** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#48]
Prerequisites
    You can find available pre-built KinesisVideoProducerJNI library in src/main/resources/lib/ for Mac (x64), Ubuntu (x64) and Raspian (x86) and Windows 10.

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/tree/master/src/main/resources/lib

However, there is no Windows 10 dll in the directory.

**Comment by zhiyua-git** [comment]
@pmtolk  Thanks for reaching out. The pre-built binary was missing in the process of release. Now it is in the latest commit. Please check it out, thanks.

**Comment by pmtolk** [comment]
Thanks got it!
