### ISSUE TITLE
The requested stream is not found or not active. (Service: AmazonKinesisVideo; Status Code: 404; Error Code: ResourceNotFoundException;

### ISSUE THREAD

**Issue by zebpaypeswani** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#59]

**Comment by addodelgrossi** [comment]
@zebpaypeswani I encountered the same problem, how did you solve it?

**Comment by zebpaypeswani** [comment]
@addodelgrossi  I used python lib.

**Comment by biswajit123** [comment]
@zebpaypeswani Which Python Lib did you use?

**Comment by tejuri** [comment]
Getting the same error. Trying to putmediademo example. It giving that the kvs is not found or not active.
I am running a docker container inside a windows machine.  The stream is active, i can see in the console

![image](https://user-images.githubusercontent.com/15131311/121267904-8e414500-c8da-11eb-9c15-29d21eb71b9a.png)
