### ISSUE TITLE
Set MDC context for internal logging

### ISSUE THREAD

**Issue by adokarasev** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#69]
Is there a way to populate MDC for internal logging? Because all HTTP requests are executed in background threads it does not propagate MDC from the application code. It is very useful for troubleshooting but looks like it's not possible. What could be a possible workaround? Is it safe to instantiate multiple KVS client?

**Comment by disa6302** [comment]
Closing this for now. 
Feel free to reopen/create an issue in the future
