### ISSUE TITLE
GetMedia API. How to get segment wise KVS stream from Getmedia and how to store in S3

### ISSUE THREAD

**Issue by hameedriswan7** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#74]
@zhiyua-git 
Using this GetMedia Api i can get KVS stream video in local but it gives single output of merged fragment so it will increase the size and override	on same output. i need video output as segment wise of single stream. how to store single KVS as fragment video  to S3.

GetMediaResult getMediaResult = builder.build().getMedia(getMediaRequest);

		System.out.println("getMedia: " + getMediaResult);
		System.out.println("contentType: " + getMediaResult.getContentType());
		System.out.println("streamname: " + getMediaRequest.getStreamName());

		OutputStream fileOutputStream = Files.newOutputStream(Paths.get("kinesis_video_merged_output.mkv"),
				StandardOpenOption.WRITE, StandardOpenOption.CREATE);
		BufferedOutputStream outputStream = new BufferedOutputStream(fileOutputStream);
		
		//An OutputSegmentMerger to combine multiple segments that share track and ebml metadata into one
	    //mkv segment.
		OutputSegmentMerger outputSegmentMerger = OutputSegmentMerger.createDefault(outputStream);
		System.out.println("outputSegmentMerger " + outputSegmentMerger);
		
		
		

		FragmentMetadataVisitor fragmentMetadataVisitor = FragmentMetadataVisitor.create();

		// A composite visitor to encapsulate the three visitors
		CompositeMkvElementVisitor mkvElementVisitor = new CompositeMkvElementVisitor(fragmentMetadataVisitor,
				outputSegmentMerger);

		System.out.println("mkvElementVisitor: " + mkvElementVisitor);
		
		StreamingMkvReader mkvReader = StreamingMkvReader
				.createDefault(new InputStreamParserByteSource(getMediaResult.getPayload()));

		System.out.println("mkvReader " + mkvReader);

		try {

			while (mkvReader.mightHaveNext()) {
				Optional<MkvElement> mkvElement = mkvReader.nextIfAvailable();
				if (mkvElement.isPresent()) {
					mkvElement.get().accept(mkvElementVisitor);
				}
			}
		} catch (Exception e) {
		}

//The moral of story is we need to get  mood analysis recognition  of KVS stream. but in AWS there is no feature for analyse mood like(Happy,Sad...) but for uploading  video analyse mood  is working fine. So i wanted to get the live stream by GETMEDIA API and store it S3 and start recognition of mood analyse. If any mistake is there please discuss with me.

**Comment by MushMal** [comment]
@hameedriswan7 your application can concatenate as many fragments as it needs and store locally for further upload into S3. An alternative is to use the new clip generation API.

I am going to resolve this but please feel free to re-open
