### ISSUE TITLE
Feature request - GetMedia() to accept start time and length of video

### ISSUE THREAD

**Issue by ahmedha** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#76]
Hello,

Requesting feature request for GetMedia() to accept two options:
- time - some sort of time index to start reading video from (could epoch time).
- length of video to read - time unit in seconds or amount and unit

Not sure if this is the right place, if not, can you please point me to where I can make such a request.

Thank you,
Ahmed.

**Comment by MushMal** [comment]
@ahmedha thanks for the question/suggestion. The GetMedia API has a start time selector: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_GetMedia.html

You can stop reading after your desired duration.

I am going to resolve this issue for now in favor of file download feature set that we are contemplating but no ETA yet.
