### ISSUE TITLE
KinesisVideoProducerJNI UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ramneetsingh** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#81]
Hi,
I am facing issue with
java.lang.UnsatisfiedLinkError: com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.getNativeLibraryVersion()Ljava/lang/String;

I have referred to 
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/16
but it does not solve the error

I've tried to set the native library path and LD_LIBRARY_PATH through command line/VM arguments, but nothing seems to work. Any help will be appreciated.

Below is the screenshot from the error
![image](https://user-images.githubusercontent.com/18351068/73742086-a1d21e00-4771-11ea-826f-2c2374ac011b.png)

**Comment by zhiyua-git** [comment]
Hi @ramneetsingh ,

Can you confirm what version of java SDK are you using? The libKinesisVideoProducer library loading would fail if the version doesn't match. Thanks.

**Comment by disa6302** [comment]
Stale issue. Closing it. Feel free to reopen in the future.

**Comment by BodapatlaKiranReddy** [comment]
@ramneetsingh @disa6302 

i am facing similar issue, any help appreciated.
i am using JDK 7 and provided KinesisVideoProducerJNI.dll library path through VM arguments.

Below is the screenshot of the error
![Screenshot 2021-01-21 160023](https://user-images.githubusercontent.com/38557349/105338671-d567bb80-5c01-11eb-8c2e-f9fdf0177219.png)

**Comment by aqiao** [comment]
@BodapatlaKiranReddy ,
I encountered the same issue. In my case ,since i modified producer-cpp-sdk for debug, after i replace the modified dylib with original one, error disappeared. Hope it will give your some hints
