### ISSUE TITLE
No media found Verify that you are streaming to us-east-1 and the fragment timecodes are correct, or download the Kinesis Video Streams Producer SDK to set up your device.

### ISSUE THREAD

**Issue by naxir** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#84]
![Issue](https://user-images.githubusercontent.com/17848552/74507810-4ea15d80-4f1f-11ea-8093-4105078f0d23.PNG)

Any help please!

**Comment by disa6302** [comment]
Hello @naxir ,

A couple of questions:

1. Are you currently running one of the applications in the producer SDK?

2. Can you post the logs here so that we can see what might be going on?

3. Which platform are you running the application in?

Thanks,
Divya

**Comment by naxir** [comment]
Hi @disa6302 , 
https://github.com/awslabs/aws-sdk-android-samples 
I am following these sample code and using **AmazonKinesisVideoDemoApp** i have configured it successfully on my android mobile and i have created account and record a stream 
but facing above error as i mentioned

**Comment by naxir** [comment]
![Stream](https://user-images.githubusercontent.com/17848552/74525145-44448b00-4f42-11ea-80fa-bb0d60d0f042.PNG)

you can check it the result

**Comment by naxir** [comment]
@disa6302 
check it also i have created video stream 
![VideoStreams](https://user-images.githubusercontent.com/17848552/74525940-2415cb80-4f44-11ea-80d1-ff2f6df1a2fa.PNG)

when i am going to click it , in media playback section i am facing above error

**Comment by MushMal** [comment]
@naxir Would you be able to get the logs from the producer side and attach?

**Comment by naxir** [comment]
![logs](https://user-images.githubusercontent.com/17848552/74628606-e8fbde00-5177-11ea-9376-619a61a8aaa5.png)

@MushMal  Please have a look

**Comment by MushMal** [comment]
@naxir I don't see any logs attached. Could you please attach the logs from the producer device to ensure that you are able to stream in the video bits. I see that you are using Android demo app. If you could collect the logcat logs from the start of the application and into a few minutes into a streaming. This way we could see whether you are successfully streaming in before we see whats going on with the consumer (HLS/MPEG-DASH) side which in case of successful streaming might be the time selection.

**Comment by naxir** [comment]
![Logs](https://user-images.githubusercontent.com/17848552/74710641-eff02280-5243-11ea-8fd5-f1711404347a.PNG)

@MushMal  Please find this attached document

**Comment by naxir** [comment]
@MushMal   & @disa6302  Thanks for helping 

I have fixed it Finally!!

**Comment by MushMal** [comment]
@naxir could you please update the thread on your findings? Looking at the small piece of the picture that contains a snippet of the log doesn't really reveal anything.

**Comment by Joseph-TSS** [comment]
@naxir how did you finish please explain?

**Comment by PhilipSlisenko** [comment]
I was following this guide: https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/producer-cpp/docker-rtsp and also faced this issue. In my case, I was indeed not streaming to the proper region as the error message suggested. Producer by default created a stream in us-west-2 and was streaming there (so you might want to delete that stream). I needed to add AWS_DEFAULT_REGION=<region-name> env var when starting producer to make it stream to the proper region.
