### ISSUE TITLE
java-install-script not found

### ISSUE THREAD

**Issue by kennycoder** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#93]
Running Dockerfile build issues an error:
chmod: cannot access './java-install-script': No such file or directory

This file cannot be found in any previous releases nor in related repo:
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp

**Comment by disa6302** [comment]
@kennycoder , 

Last week, we moved to a cmake build system in producer CPP SDK and have not updated the Dockerfile for java yet. We will work on updating the docker file. Thank you for your patience in the meantime!

**Comment by disa6302** [comment]
@kennycoder , 

I have pushed a change to solve this issue. You can grab the latest master and try it out. 
Resolving this for now. Feel free to open a new issue if you face any problems!
