### ISSUE TITLE
How to generate HLS url from Aws Kinesis video stream using java sdk

### ISSUE THREAD

**Issue by awslearne** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#96]

**Comment by MushMal** [comment]
This project is the Java producer SDK and it doesn't have any ability to generate HLS. You might need to use AWS SDK in order to do that. https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kinesisvideo/model/GetHLSStreamingSessionURLRequest.html
