### ISSUE TITLE
 create new stream using AmazonKinesisVideoClient

### ISSUE THREAD

**Issue by awslearne** [awslabs/amazon-kinesis-video-streams-producer-sdk-java#99]
Not able to create new stream using AmazonKinesisVideoClient class from aws-java-sdk-bom (1.11.602)
Getting error as:
[AV.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/files/4705257/AV.log)

According to attached log,im not able to find root cause for getting error in service name : "AWSAcuityReader" .
Im using correct credentials and connected to proper Vpc.

Any solution for this issue?

**Comment by lherman-cs** [comment]
That definitely looks like a bug. @disa6302 maybe can comment on this?

**Comment by MushMal** [comment]
@awslearne could you please include a little more information on your scenario? What repository and which asset/sample are you using and whether you made any changes locally?

**Comment by MushMal** [comment]
Resolving as stale
